#!/bin/bash

tag="snap.$SNAP_INSTANCE_NAME.hook.prepare-slot-config"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)


echo "Prepare connect slot for snap $SNAP_INSTANCE_NAME"


# Setting a json object directly isn't possible.
snapctl set :defaults -t snap='{
    "gemma4": {
        "engine": "intel-gpu",
        "model": "e2b-q4-k-m-gguf"
    }
}'
