#!/bin/bash

tag="snap.$SNAP_INSTANCE_NAME.hook.prepare-plug-config"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)


echo "Preparing plug config for snap $SNAP_INSTANCE_NAME"

snapctl set :config engine=cpu
