name: gemma3-jane
base: core26 
version: producer-only
summary: Single-line elevator pitch for your amazing snap 
description: This is my-snap's description. 

grade: devel
confinement: strict

slots:
  # To share provider details with other snaps
  provider:
    interface: content
    content: inference-provider
    source:
      read:
        # There are better locations for this, but they are not supported:
        # 1: Use of a tempfs (/run/snap.gemma3-jane/provider/gemma3-jane, /tmp/provider/gemma3-jane) breaks content sharing:
        # Directory gets mounted but not the content. 
        # 2: User scoped directories (SNAP_USER_COMMON, SNAP_USER_DATA) are not supported by snapd for content sharing:
        # update.go:193: cannot change mount namespace according to change mount (/snap/gemma3-jane/x1//provider/gemma3-jane /snap/consumer/x1/share/gemma3-jane none bind,ro 0 0): cannot split unclean path "/snap/gemma3-jane/x1//provider/gemma3-jane"
        - $SNAP_COMMON/share/provider
  # To share model weights
  # This is currently not possible because the components cannot be shared via the content interface.
  # models:
  #   interface: content
  #   content: inference-models
  #   source:
  #     read:
  #     # Attempted paths:
  #     # 1: $SNAP/components/$SNAP_REVISION/model-a:
  #     # snap "gemma3-jane" has bad plugs or slots: models (content interface path is not clean: "$SNAP/../components/$SNAP_REVISION/model-a")
  #     # 2: /snap/gemma3-jane/components/$SNAP_REVISION/model-a:
  #     # $SNAP_REVISION is not set here
  #     # 3: /snap/gemma3-jane/components:
  #     # mounted empty on the consumer side
  #     - <path to component>


parts:
  myfiles:
    plugin: dump
    source: .
    organize:
      model.gguf: (component/model-a)

apps:
  gemma:
    command: app.sh

components:
  model-a:
    type: standard
    summary: Test component
    description: Test component
