#!/bin/bash

tag="snap.$SNAP_INSTANCE_NAME.hook.connect-plug-config"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)


echo "Connect plug config for snap $SNAP_INSTANCE_NAME"

defaults="$(snapctl get :defaults --slot snap.gemma4)"

echo "engine: "$defaults""

# dump the defaults to a file for debugging
echo "$defaults" > /tmp/defaults.json
