#!/bin/bash

tag="snap.$SNAP_INSTANCE_NAME.hook.prepare-slot-config"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)


echo "Preparing slot config for snap $SNAP_INSTANCE_NAME"

snapctl set :config myname=$SNAP_INSTANCE_NAME
