#!/bin/bash

tag="snap.$SNAP_INSTANCE_NAME.hook.connect-plug-config"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)


echo "Connect plug config for snap $SNAP_INSTANCE_NAME"

# Read the defaults set by the provider snap
defaults="$(snapctl get :defaults --slot snap.gemma3)"

echo "engine: "$defaults""
# Prints:
# {
#   "engine": "intel-gpu",
#   "model": "e2b-q4-k-m-gguf"
# }

set -o pipefail

engine=$(echo "$defaults" | jq -r .engine)
model=$(echo "$defaults" | jq -r .model)

# Store the extracted values as snap options, the same way a Gadget snap would set them
snapctl set engine="$engine"
snapctl set model="$model"
snapctl set test="test"
