#!/bin/bash

tag="snap.$SNAP_INSTANCE_NAME.hook.default-configure"

# Redirect stdout to stdout+syslog
exec 1> >(tee >(logger --tag=$tag))
# Redirect stderr to stderr+syslog
exec 2> >(logger --stderr --priority error --tag=$tag)


echo "Default configure hook for snap $SNAP_INSTANCE_NAME"

# Why use default configure hook?
# - It runs after the connect hook
# - It has access to defaults seeded from a gadget on Ubuntu Core (install hook does not)

# Do something with the configurations
snapctl get engine
snapctl get model
#modelctl use-engine --auto
snapctl install +test

# Discard the values after use
snapctl unset engine
snapctl unset model
